version: '3.7'
services:
  php-fpm:
    build: './docker/php-fpm'
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www:cached

  nginx:
    build: './docker/nginx'
    ports:
      - 8080:80
    volumes:
      - './:/var/www:cached'
    depends_on:
      - php-fpm

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: characters
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  database_data:

###> doctrine/doctrine-bundle ###
